dist: trusty
sudo: required

language: common-lisp

env:
  matrix:
    - LISP=sbcl

addons:
  apt:
   packages:
     - openssh-server
     - openssl
     - libssh2-1
  ssh_known_hosts:
    - localhost
    - 0.0.0.0

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash
  # create a group for testing
  - sudo addgroup ssh2test
  - sudo adduser --group ssh2test test1 <<EOF
    test1
    test1
    EOF
  - sudo adduser --group ssh2test test2 <<EOF
    test2
    test2
    EOF
  - sudo ssh-keyscan -t $TRAVIS_SSH_KEY_TYPES -H localhost 2>&1 | tee -a ~test1/.ssh/known_hosts
  - sudo ssh-keyscan -t $TRAVIS_SSH_KEY_TYPES -H 0.0.0.0 2>&1 | tee -a ~test1/.ssh/known_hosts
  - sudo ssh-keyscan -t $TRAVIS_SSH_KEY_TYPES -H localhost 2>&1 | tee -a ~test2/.ssh/known_hosts
  - sudo ssh-keyscan -t $TRAVIS_SSH_KEY_TYPES -H 0.0.0.0 2>&1 | tee -a ~test2/.ssh/known_hosts
  - sudo su - test1 -c "ssh -vvv localhost"
  # add localhost to known_hosts
  # - ssh-keyscan -vvv -t rsa localhost >> $HOME/.ssh/known_hosts

script:
  - cl -e '(ql:quickload :hu.dwim.stefil)'
       -e '(ql:quickload :cffi-grovel)'
       -e '(ql:quickload :libssh2.test)'
       -e '(setf libssh2.test::*user1* "test1" libssh2.test::*password1* "test1")'
       -e '(setf libssh2.test::*user2* "test2" libssh2.test::*password2* "test2")'
       -e '(libssh2.test:run-all-tests)'
  - ls -al /tmp/